//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Kebler.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Dialogs {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Kebler.Resources.Dialogs", typeof(Dialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ATD_Cancel {
            get {
                return ResourceManager.GetString("ATD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        internal static string ATD_Connection {
            get {
                return ResourceManager.GetString("ATD_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this dialog.
        /// </summary>
        internal static string ATD_DontShowAddTorrentDialog {
            get {
                return ResourceManager.GetString("ATD_DontShowAddTorrentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Dirrectory:.
        /// </summary>
        internal static string ATD_DownloadDIr {
            get {
                return ResourceManager.GetString("ATD_DownloadDIr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Limit:.
        /// </summary>
        internal static string ATD_DownloadLimit {
            get {
                return ResourceManager.GetString("ATD_DownloadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer Limit:.
        /// </summary>
        internal static string ATD_PeerLimit {
            get {
                return ResourceManager.GetString("ATD_PeerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start torrent.
        /// </summary>
        internal static string ATD_StartTorrent {
            get {
                return ResourceManager.GetString("ATD_StartTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ATD_Stop {
            get {
                return ResourceManager.GetString("ATD_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent file exists.
        /// </summary>
        internal static string ATD_TorrentExist {
            get {
                return ResourceManager.GetString("ATD_TorrentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent File Path:.
        /// </summary>
        internal static string ATD_TorrentFilePath {
            get {
                return ResourceManager.GetString("ATD_TorrentFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Limit:.
        /// </summary>
        internal static string ATD_UploadLimit {
            get {
                return ResourceManager.GetString("ATD_UploadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BTNS_Cancel {
            get {
                return ResourceManager.GetString("BTNS_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BTNS_No {
            get {
                return ResourceManager.GetString("BTNS_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string BTNS_OK {
            get {
                return ResourceManager.GetString("BTNS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BTNS_Yes {
            get {
                return ResourceManager.GetString("BTNS_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while applying settings. Some preferences may be not applied correctly.
        /// </summary>
        internal static string ConfigApllyError {
            get {
                return ResourceManager.GetString("ConfigApllyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost. Reconnect and try again.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove with data.
        /// </summary>
        internal static string RMT_RemoveWithData {
            get {
                return ResourceManager.GetString("RMT_RemoveWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all this torrents?.
        /// </summary>
        internal static string RMT_Title {
            get {
                return ResourceManager.GetString("RMT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        internal static string Title_AddTorrentDialog {
            get {
                return ResourceManager.GetString("Title_AddTorrentDialog", resourceCulture);
            }
        }
    }
}
