//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Kebler.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class HeaderMenu {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeaderMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Kebler.Resources.HeaderMenu", typeof(HeaderMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MI_About {
            get {
                return ResourceManager.GetString("MI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        internal static string MI_AddTorrent {
            get {
                return ResourceManager.GetString("MI_AddTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For New Version.
        /// </summary>
        internal static string MI_Check {
            get {
                return ResourceManager.GetString("MI_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        internal static string MI_CM {
            get {
                return ResourceManager.GetString("MI_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Developer.
        /// </summary>
        internal static string MI_Contact {
            get {
                return ResourceManager.GetString("MI_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Mi_Info {
            get {
                return ResourceManager.GetString("Mi_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MI_lang {
            get {
                return ResourceManager.GetString("MI_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Problem.
        /// </summary>
        internal static string MI_Report {
            get {
                return ResourceManager.GetString("MI_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added date.
        /// </summary>
        internal static string MI_Sort_AddedDate {
            get {
                return ResourceManager.GetString("MI_Sort_AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed.
        /// </summary>
        internal static string MI_Sort_DownloadSpeed {
            get {
                return ResourceManager.GetString("MI_Sort_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string MI_Sort_Uploaded {
            get {
                return ResourceManager.GetString("MI_Sort_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload speed.
        /// </summary>
        internal static string MI_Sort_UploadSpeed {
            get {
                return ResourceManager.GetString("MI_Sort_UploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string MI_SortHigh {
            get {
                return ResourceManager.GetString("MI_SortHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string MI_SortLow {
            get {
                return ResourceManager.GetString("MI_SortLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string MI_Torrent {
            get {
                return ResourceManager.GetString("MI_Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MI_View {
            get {
                return ResourceManager.GetString("MI_View", resourceCulture);
            }
        }
    }
}
