//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kebler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kebler.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Settings From Server.
        /// </summary>
        internal static string ATD_RetrievingSettings {
            get {
                return ResourceManager.GetString("ATD_RetrievingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Cat_Active {
            get {
                return ResourceManager.GetString("Cat_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Cat_AllTorrents {
            get {
                return ResourceManager.GetString("Cat_AllTorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Cat_Downloading {
            get {
                return ResourceManager.GetString("Cat_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Cat_Ended {
            get {
                return ResourceManager.GetString("Cat_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Cat_Error {
            get {
                return ResourceManager.GetString("Cat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Cat_InActive {
            get {
                return ResourceManager.GetString("Cat_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Cat_Stopped {
            get {
                return ResourceManager.GetString("Cat_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kebler.
        /// </summary>
        internal static string Kebler {
            get {
                return ResourceManager.GetString("Kebler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MI_About {
            get {
                return ResourceManager.GetString("MI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Magnet.
        /// </summary>
        internal static string MI_AddMagnet {
            get {
                return ResourceManager.GetString("MI_AddMagnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        internal static string MI_AddTorrent {
            get {
                return ResourceManager.GetString("MI_AddTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckUpdates For New Version.
        /// </summary>
        internal static string MI_Check {
            get {
                return ResourceManager.GetString("MI_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        internal static string MI_CM {
            get {
                return ResourceManager.GetString("MI_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Developer.
        /// </summary>
        internal static string MI_Contact {
            get {
                return ResourceManager.GetString("MI_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MI_Exit {
            get {
                return ResourceManager.GetString("MI_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Mi_Info {
            get {
                return ResourceManager.GetString("Mi_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kebler.
        /// </summary>
        internal static string MI_Kebler {
            get {
                return ResourceManager.GetString("MI_Kebler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MI_lang {
            get {
                return ResourceManager.GetString("MI_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs.
        /// </summary>
        internal static string MI_Logs {
            get {
                return ResourceManager.GetString("MI_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string MI_Props {
            get {
                return ResourceManager.GetString("MI_Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Problem.
        /// </summary>
        internal static string MI_Report {
            get {
                return ResourceManager.GetString("MI_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string MI_Servers {
            get {
                return ResourceManager.GetString("MI_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added date.
        /// </summary>
        internal static string MI_Sort_AddedDate {
            get {
                return ResourceManager.GetString("MI_Sort_AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed.
        /// </summary>
        internal static string MI_Sort_DownloadSpeed {
            get {
                return ResourceManager.GetString("MI_Sort_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string MI_Sort_Uploaded {
            get {
                return ResourceManager.GetString("MI_Sort_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload speed.
        /// </summary>
        internal static string MI_Sort_UploadSpeed {
            get {
                return ResourceManager.GetString("MI_Sort_UploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string MI_SortHigh {
            get {
                return ResourceManager.GetString("MI_SortHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string MI_SortLow {
            get {
                return ResourceManager.GetString("MI_SortLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string MI_Torrent {
            get {
                return ResourceManager.GetString("MI_Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MI_View {
            get {
                return ResourceManager.GetString("MI_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string MoreInfo_FilesTab {
            get {
                return ResourceManager.GetString("MoreInfo_FilesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc, to hide.
        /// </summary>
        internal static string MoreInfo_HideHint {
            get {
                return ResourceManager.GetString("MoreInfo_HideHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peers.
        /// </summary>
        internal static string MoreInfo_Peers {
            get {
                return ResourceManager.GetString("MoreInfo_Peers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string MoreInfo_Peers_Client {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encyption.
        /// </summary>
        internal static string MoreInfo_Peers_Encryption {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string MoreInfo_Peers_Host {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string MoreInfo_Peers_Progress {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Speed.
        /// </summary>
        internal static string MoreInfo_PeersRateToClient {
            get {
                return ResourceManager.GetString("MoreInfo_PeersRateToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Speed.
        /// </summary>
        internal static string MoreInfo_PeersRateToPeer {
            get {
                return ResourceManager.GetString("MoreInfo_PeersRateToPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers.
        /// </summary>
        internal static string MoreInfo_Trackers {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string MoreInfo_Trackers_Name {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string MoreInfo_Trackers_Seeds {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers_Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds.
        /// </summary>
        internal static string MoreInfo_Trackers_Status {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        internal static string QA_AddTorrent {
            get {
                return ResourceManager.GetString("QA_AddTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Bottom.
        /// </summary>
        internal static string QA_MoveBot {
            get {
                return ResourceManager.GetString("QA_MoveBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string QA_MoveDown {
            get {
                return ResourceManager.GetString("QA_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Top.
        /// </summary>
        internal static string QA_MoveTop {
            get {
                return ResourceManager.GetString("QA_MoveTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string QA_MoveUp {
            get {
                return ResourceManager.GetString("QA_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string QA_Pause {
            get {
                return ResourceManager.GetString("QA_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause All.
        /// </summary>
        internal static string QA_PauseAll {
            get {
                return ResourceManager.GetString("QA_PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string QA_Priority {
            get {
                return ResourceManager.GetString("QA_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string QA_Queue {
            get {
                return ResourceManager.GetString("QA_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reannounce (get more peers).
        /// </summary>
        internal static string QA_Reannounce {
            get {
                return ResourceManager.GetString("QA_Reannounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string QA_Remove {
            get {
                return ResourceManager.GetString("QA_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Data.
        /// </summary>
        internal static string QA_RemoveData {
            get {
                return ResourceManager.GetString("QA_RemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string QA_Rename {
            get {
                return ResourceManager.GetString("QA_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string QA_Resume {
            get {
                return ResourceManager.GetString("QA_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All.
        /// </summary>
        internal static string QA_ResumeAll {
            get {
                return ResourceManager.GetString("QA_ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Data Location....
        /// </summary>
        internal static string QA_SetLoc {
            get {
                return ResourceManager.GetString("QA_SetLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Mode.
        /// </summary>
        internal static string QA_Slow {
            get {
                return ResourceManager.GetString("QA_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string QA_Verify {
            get {
                return ResourceManager.GetString("QA_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RetryConnection {
            get {
                return ResourceManager.GetString("RetryConnection", resourceCulture);
            }
        }
    }
}
