//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Kebler.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Strings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Kebler.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Cat_Active {
            get {
                return ResourceManager.GetString("Cat_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Cat_AllTorrents {
            get {
                return ResourceManager.GetString("Cat_AllTorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Cat_Downloading {
            get {
                return ResourceManager.GetString("Cat_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Cat_Ended {
            get {
                return ResourceManager.GetString("Cat_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Cat_Error {
            get {
                return ResourceManager.GetString("Cat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Cat_InActive {
            get {
                return ResourceManager.GetString("Cat_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Cat_Stopped {
            get {
                return ResourceManager.GetString("Cat_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kebler.
        /// </summary>
        internal static string Kebler {
            get {
                return ResourceManager.GetString("Kebler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        internal static string QA_AddTorrent {
            get {
                return ResourceManager.GetString("QA_AddTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string QA_Pause {
            get {
                return ResourceManager.GetString("QA_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause All.
        /// </summary>
        internal static string QA_PauseAll {
            get {
                return ResourceManager.GetString("QA_PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string QA_Remove {
            get {
                return ResourceManager.GetString("QA_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Data.
        /// </summary>
        internal static string QA_RemoveData {
            get {
                return ResourceManager.GetString("QA_RemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string QA_Resume {
            get {
                return ResourceManager.GetString("QA_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume All.
        /// </summary>
        internal static string QA_ResumeAll {
            get {
                return ResourceManager.GetString("QA_ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Mode.
        /// </summary>
        internal static string QA_Slow {
            get {
                return ResourceManager.GetString("QA_Slow", resourceCulture);
            }
        }
    }
}
