//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kebler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Windows {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Windows() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kebler.Resources.Windows", typeof(Windows).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ask for password.
        /// </summary>
        internal static string CM_AskForPassword {
            get {
                return ResourceManager.GetString("CM_AskForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string CM_AuthSection {
            get {
                return ResourceManager.GetString("CM_AuthSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CM_Cancel {
            get {
                return ResourceManager.GetString("CM_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auth.
        /// </summary>
        internal static string CM_IsAuthEnabled {
            get {
                return ResourceManager.GetString("CM_IsAuthEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string CM_LanSection {
            get {
                return ResourceManager.GetString("CM_LanSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string CM_Login {
            get {
                return ResourceManager.GetString("CM_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string CM_Ok {
            get {
                return ResourceManager.GetString("CM_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string CM_PSWD {
            get {
                return ResourceManager.GetString("CM_PSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC Path:.
        /// </summary>
        internal static string CM_RPCPath {
            get {
                return ResourceManager.GetString("CM_RPCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        internal static string CM_ServerHost {
            get {
                return ResourceManager.GetString("CM_ServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string CM_ServerPort {
            get {
                return ResourceManager.GetString("CM_ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string CM_ServerTitle {
            get {
                return ResourceManager.GetString("CM_ServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        internal static string CM_SSLEnabled {
            get {
                return ResourceManager.GetString("CM_SSLEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CM_Tab_General {
            get {
                return ResourceManager.GetString("CM_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string CM_TestConnection {
            get {
                return ResourceManager.GetString("CM_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CM_TestConnectionBad {
            get {
                return ResourceManager.GetString("CM_TestConnectionBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string CM_TestConnectionGood {
            get {
                return ResourceManager.GetString("CM_TestConnectionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        internal static string CM_Title {
            get {
                return ResourceManager.GetString("CM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string MW_ConnectingText {
            get {
                return ResourceManager.GetString("MW_ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cant be empty.
        /// </summary>
        internal static string MW_PAsswordCantBeEmpty {
            get {
                return ResourceManager.GetString("MW_PAsswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing session.
        /// </summary>
        internal static string MW_StatusText_CloseSession {
            get {
                return ResourceManager.GetString("MW_StatusText_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to session.
        /// </summary>
        internal static string MW_StatusText_Session {
            get {
                return ResourceManager.GetString("MW_StatusText_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updateing settings.
        /// </summary>
        internal static string MW_StatusText_Settings {
            get {
                return ResourceManager.GetString("MW_StatusText_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating stats.
        /// </summary>
        internal static string MW_StatusText_Stats {
            get {
                return ResourceManager.GetString("MW_StatusText_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting torrents.
        /// </summary>
        internal static string MW_StatusText_Torrents {
            get {
                return ResourceManager.GetString("MW_StatusText_Torrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time:.
        /// </summary>
        internal static string Stats_ActiveTime {
            get {
                return ResourceManager.GetString("Stats_ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        internal static string Stats_Downloaded {
            get {
                return ResourceManager.GetString("Stats_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        internal static string Stats_Uploaded {
            get {
                return ResourceManager.GetString("Stats_Uploaded", resourceCulture);
            }
        }
      
    }
}
