//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kebler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kebler.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ATD_Add {
            get {
                return ResourceManager.GetString("ATD_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ATD_Cancel {
            get {
                return ResourceManager.GetString("ATD_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        public static string ATD_Connection {
            get {
                return ResourceManager.GetString("ATD_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this dialog.
        /// </summary>
        public static string ATD_DontShowAddTorrentDialog {
            get {
                return ResourceManager.GetString("ATD_DontShowAddTorrentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Dirrectory:.
        /// </summary>
        public static string ATD_DownloadDIr {
            get {
                return ResourceManager.GetString("ATD_DownloadDIr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Limit:.
        /// </summary>
        public static string ATD_DownloadLimit {
            get {
                return ResourceManager.GetString("ATD_DownloadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string ATD_Files {
            get {
                return ResourceManager.GetString("ATD_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer Limit:.
        /// </summary>
        public static string ATD_PeerLimit {
            get {
                return ResourceManager.GetString("ATD_PeerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Settings From Server.
        /// </summary>
        public static string ATD_RetrievingSettings {
            get {
                return ResourceManager.GetString("ATD_RetrievingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start torrent.
        /// </summary>
        public static string ATD_StartTorrent {
            get {
                return ResourceManager.GetString("ATD_StartTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ATD_Stop {
            get {
                return ResourceManager.GetString("ATD_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent file exists.
        /// </summary>
        public static string ATD_TorrentExist {
            get {
                return ResourceManager.GetString("ATD_TorrentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent File Path:.
        /// </summary>
        public static string ATD_TorrentFilePath {
            get {
                return ResourceManager.GetString("ATD_TorrentFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Limit:.
        /// </summary>
        public static string ATD_UploadLimit {
            get {
                return ResourceManager.GetString("ATD_UploadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BTNS_Cancel {
            get {
                return ResourceManager.GetString("BTNS_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BTNS_No {
            get {
                return ResourceManager.GetString("BTNS_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BTNS_OK {
            get {
                return ResourceManager.GetString("BTNS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BTNS_Yes {
            get {
                return ResourceManager.GetString("BTNS_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Cat_Active {
            get {
                return ResourceManager.GetString("Cat_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Cat_AllTorrents {
            get {
                return ResourceManager.GetString("Cat_AllTorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Cat_Downloading {
            get {
                return ResourceManager.GetString("Cat_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Cat_Ended {
            get {
                return ResourceManager.GetString("Cat_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Cat_Error {
            get {
                return ResourceManager.GetString("Cat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Cat_InActive {
            get {
                return ResourceManager.GetString("Cat_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Cat_Stopped {
            get {
                return ResourceManager.GetString("Cat_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ask for password.
        /// </summary>
        public static string CM_AskForPassword {
            get {
                return ResourceManager.GetString("CM_AskForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string CM_AuthSection {
            get {
                return ResourceManager.GetString("CM_AuthSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CM_Cancel {
            get {
                return ResourceManager.GetString("CM_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auth.
        /// </summary>
        public static string CM_IsAuthEnabled {
            get {
                return ResourceManager.GetString("CM_IsAuthEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string CM_LanSection {
            get {
                return ResourceManager.GetString("CM_LanSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string CM_Login {
            get {
                return ResourceManager.GetString("CM_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string CM_Ok {
            get {
                return ResourceManager.GetString("CM_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string CM_PSWD {
            get {
                return ResourceManager.GetString("CM_PSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC Path:.
        /// </summary>
        public static string CM_RPCPath {
            get {
                return ResourceManager.GetString("CM_RPCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string CM_ServerHost {
            get {
                return ResourceManager.GetString("CM_ServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string CM_ServerPort {
            get {
                return ResourceManager.GetString("CM_ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string CM_ServerTitle {
            get {
                return ResourceManager.GetString("CM_ServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        public static string CM_SSLEnabled {
            get {
                return ResourceManager.GetString("CM_SSLEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string CM_Tab_General {
            get {
                return ResourceManager.GetString("CM_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string CM_TestConnection {
            get {
                return ResourceManager.GetString("CM_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CM_TestConnectionBad {
            get {
                return ResourceManager.GetString("CM_TestConnectionBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string CM_TestConnectionGood {
            get {
                return ResourceManager.GetString("CM_TestConnectionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        public static string CM_Title {
            get {
                return ResourceManager.GetString("CM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while applying settings. Some preferences may be not applied correctly.
        /// </summary>
        public static string ConfigApllyError {
            get {
                return ResourceManager.GetString("ConfigApllyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost. Reconnect and try again.
        /// </summary>
        public static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string DialogBox_EnterPWD {
            get {
                return ResourceManager.GetString("DialogBox_EnterPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name unknown.
        /// </summary>
        public static string EX_Host {
            get {
                return ResourceManager.GetString("EX_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kebler.
        /// </summary>
        public static string Kebler {
            get {
                return ResourceManager.GetString("Kebler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MI_About {
            get {
                return ResourceManager.GetString("MI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Magnet.
        /// </summary>
        public static string MI_AddMagnet {
            get {
                return ResourceManager.GetString("MI_AddMagnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        public static string MI_AddTorrent {
            get {
                return ResourceManager.GetString("MI_AddTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Updates.
        /// </summary>
        public static string MI_Check {
            get {
                return ResourceManager.GetString("MI_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Manager.
        /// </summary>
        public static string MI_CM {
            get {
                return ResourceManager.GetString("MI_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Developer.
        /// </summary>
        public static string MI_Contact {
            get {
                return ResourceManager.GetString("MI_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        public static string MI_Downloaded {
            get {
                return ResourceManager.GetString("MI_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download limit:.
        /// </summary>
        public static string MI_DownloadLimit {
            get {
                return ResourceManager.GetString("MI_DownloadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string MI_Error {
            get {
                return ResourceManager.GetString("MI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MI_Exit {
            get {
                return ResourceManager.GetString("MI_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Mi_Info {
            get {
                return ResourceManager.GetString("Mi_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kebler.
        /// </summary>
        public static string MI_Kebler {
            get {
                return ResourceManager.GetString("MI_Kebler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MI_lang {
            get {
                return ResourceManager.GetString("MI_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last active:.
        /// </summary>
        public static string MI_LastActive {
            get {
                return ResourceManager.GetString("MI_LastActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs.
        /// </summary>
        public static string MI_Logs {
            get {
                return ResourceManager.GetString("MI_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max peers:.
        /// </summary>
        public static string MI_MaxPeers {
            get {
                return ResourceManager.GetString("MI_MaxPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peers:.
        /// </summary>
        public static string MI_Peers {
            get {
                return ResourceManager.GetString("MI_Peers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string MI_Prefs {
            get {
                return ResourceManager.GetString("MI_Prefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MI_Props {
            get {
                return ResourceManager.GetString("MI_Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining:.
        /// </summary>
        public static string MI_Remaining {
            get {
                return ResourceManager.GetString("MI_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Problem.
        /// </summary>
        public static string MI_Report {
            get {
                return ResourceManager.GetString("MI_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds:.
        /// </summary>
        public static string MI_Seeds {
            get {
                return ResourceManager.GetString("MI_Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string MI_Servers {
            get {
                return ResourceManager.GetString("MI_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share ratio:.
        /// </summary>
        public static string MI_ShareRatio {
            get {
                return ResourceManager.GetString("MI_ShareRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added date.
        /// </summary>
        public static string MI_Sort_AddedDate {
            get {
                return ResourceManager.GetString("MI_Sort_AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed.
        /// </summary>
        public static string MI_Sort_DownloadSpeed {
            get {
                return ResourceManager.GetString("MI_Sort_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string MI_Sort_Uploaded {
            get {
                return ResourceManager.GetString("MI_Sort_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload speed.
        /// </summary>
        public static string MI_Sort_UploadSpeed {
            get {
                return ResourceManager.GetString("MI_Sort_UploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string MI_SortHigh {
            get {
                return ResourceManager.GetString("MI_SortHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string MI_SortLow {
            get {
                return ResourceManager.GetString("MI_SortLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed:.
        /// </summary>
        public static string MI_SpeedDownload {
            get {
                return ResourceManager.GetString("MI_SpeedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string MI_State {
            get {
                return ResourceManager.GetString("MI_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        public static string MI_Torrent {
            get {
                return ResourceManager.GetString("MI_Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker updated:.
        /// </summary>
        public static string MI_TrackerUpate {
            get {
                return ResourceManager.GetString("MI_TrackerUpate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string MI_Uploaded {
            get {
                return ResourceManager.GetString("MI_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload limit:.
        /// </summary>
        public static string MI_UploadLimit {
            get {
                return ResourceManager.GetString("MI_UploadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload speed:.
        /// </summary>
        public static string MI_UploadSpeed {
            get {
                return ResourceManager.GetString("MI_UploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MI_View {
            get {
                return ResourceManager.GetString("MI_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasted:.
        /// </summary>
        public static string MI_Wasted {
            get {
                return ResourceManager.GetString("MI_Wasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tracker.
        /// </summary>
        public static string MoreInfo_DeleteTrackerBtn {
            get {
                return ResourceManager.GetString("MoreInfo_DeleteTrackerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MoreInfo_FilesTab {
            get {
                return ResourceManager.GetString("MoreInfo_FilesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc, to hide.
        /// </summary>
        public static string MoreInfo_HideHint {
            get {
                return ResourceManager.GetString("MoreInfo_HideHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peers.
        /// </summary>
        public static string MoreInfo_Peers {
            get {
                return ResourceManager.GetString("MoreInfo_Peers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string MoreInfo_Peers_Client {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string MoreInfo_Peers_Encryption {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string MoreInfo_Peers_Host {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string MoreInfo_Peers_Progress {
            get {
                return ResourceManager.GetString("MoreInfo_Peers_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Speed.
        /// </summary>
        public static string MoreInfo_PeersRateToClient {
            get {
                return ResourceManager.GetString("MoreInfo_PeersRateToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Speed.
        /// </summary>
        public static string MoreInfo_PeersRateToPeer {
            get {
                return ResourceManager.GetString("MoreInfo_PeersRateToPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers.
        /// </summary>
        public static string MoreInfo_Trackers {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string MoreInfo_Trackers_Name {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MoreInfo_Trackers_Seeds {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers_Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds.
        /// </summary>
        public static string MoreInfo_Trackers_Status {
            get {
                return ResourceManager.GetString("MoreInfo_Trackers_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new name.
        /// </summary>
        public static string MSG_InterNewName {
            get {
                return ResourceManager.GetString("MSG_InterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert link to torrent file or magnet.
        /// </summary>
        public static string MSG_LinkOrMagnet {
            get {
                return ResourceManager.GetString("MSG_LinkOrMagnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only one torrent.
        /// </summary>
        public static string MSG_OnlyOneTorrent {
            get {
                return ResourceManager.GetString("MSG_OnlyOneTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select torrent.
        /// </summary>
        public static string MSG_SelectOneTorrent {
            get {
                return ResourceManager.GetString("MSG_SelectOneTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string MW_ConnectingText {
            get {
                return ResourceManager.GetString("MW_ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cant be empty.
        /// </summary>
        public static string MW_PAsswordCantBeEmpty {
            get {
                return ResourceManager.GetString("MW_PAsswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing session.
        /// </summary>
        public static string MW_StatusText_CloseSession {
            get {
                return ResourceManager.GetString("MW_StatusText_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to session.
        /// </summary>
        public static string MW_StatusText_Session {
            get {
                return ResourceManager.GetString("MW_StatusText_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updateing settings.
        /// </summary>
        public static string MW_StatusText_Settings {
            get {
                return ResourceManager.GetString("MW_StatusText_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating stats.
        /// </summary>
        public static string MW_StatusText_Stats {
            get {
                return ResourceManager.GetString("MW_StatusText_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting torrents.
        /// </summary>
        public static string MW_StatusText_Torrents {
            get {
                return ResourceManager.GetString("MW_StatusText_Torrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        public static string QA_AddTorrent {
            get {
                return ResourceManager.GetString("QA_AddTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy magnet link.
        /// </summary>
        public static string QA_CopyMagnet {
            get {
                return ResourceManager.GetString("QA_CopyMagnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Bottom.
        /// </summary>
        public static string QA_MoveBot {
            get {
                return ResourceManager.GetString("QA_MoveBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string QA_MoveDown {
            get {
                return ResourceManager.GetString("QA_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Top.
        /// </summary>
        public static string QA_MoveTop {
            get {
                return ResourceManager.GetString("QA_MoveTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string QA_MoveUp {
            get {
                return ResourceManager.GetString("QA_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string QA_Pause {
            get {
                return ResourceManager.GetString("QA_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause All.
        /// </summary>
        public static string QA_PauseAll {
            get {
                return ResourceManager.GetString("QA_PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string QA_Priority {
            get {
                return ResourceManager.GetString("QA_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string QA_Properties {
            get {
                return ResourceManager.GetString("QA_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QA_Queue {
            get {
                return ResourceManager.GetString("QA_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reannounce (get more peers).
        /// </summary>
        public static string QA_Reannounce {
            get {
                return ResourceManager.GetString("QA_Reannounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string QA_Remove {
            get {
                return ResourceManager.GetString("QA_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Data.
        /// </summary>
        public static string QA_RemoveData {
            get {
                return ResourceManager.GetString("QA_RemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string QA_Rename {
            get {
                return ResourceManager.GetString("QA_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string QA_Resume {
            get {
                return ResourceManager.GetString("QA_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All.
        /// </summary>
        public static string QA_ResumeAll {
            get {
                return ResourceManager.GetString("QA_ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Data Location....
        /// </summary>
        public static string QA_SetLoc {
            get {
                return ResourceManager.GetString("QA_SetLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Mode.
        /// </summary>
        public static string QA_Slow {
            get {
                return ResourceManager.GetString("QA_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string QA_Verify {
            get {
                return ResourceManager.GetString("QA_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryConnection {
            get {
                return ResourceManager.GetString("RetryConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove with data.
        /// </summary>
        public static string RMT_RemoveWithData {
            get {
                return ResourceManager.GetString("RMT_RemoveWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all this torrents?.
        /// </summary>
        public static string RMT_Title {
            get {
                return ResourceManager.GetString("RMT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ssdfdsfdsfdsfs.
        /// </summary>
        public static string sdsd {
            get {
                return ResourceManager.GetString("sdsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new location for %d torrents.
        /// </summary>
        public static string SetLocForMany {
            get {
                return ResourceManager.GetString("SetLocForMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new location.
        /// </summary>
        public static string SetLocOnce {
            get {
                return ResourceManager.GetString("SetLocOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time:.
        /// </summary>
        public static string Stats_ActiveTime {
            get {
                return ResourceManager.GetString("Stats_ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        public static string Stats_Downloaded {
            get {
                return ResourceManager.GetString("Stats_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string Stats_Uploaded {
            get {
                return ResourceManager.GetString("Stats_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added on:.
        /// </summary>
        public static string TI_AddedOn {
            get {
                return ResourceManager.GetString("TI_AddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string TI_Comment {
            get {
                return ResourceManager.GetString("TI_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed on:.
        /// </summary>
        public static string TI_CompletedOn {
            get {
                return ResourceManager.GetString("TI_CompletedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on:.
        /// </summary>
        public static string TI_CreatedOn {
            get {
                return ResourceManager.GetString("TI_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash:.
        /// </summary>
        public static string TI_Hash {
            get {
                return ResourceManager.GetString("TI_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hashfails.
        /// </summary>
        public static string TI_hashfails {
            get {
                return ResourceManager.GetString("TI_hashfails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnet link:.
        /// </summary>
        public static string TI_Magnet {
            get {
                return ResourceManager.GetString("TI_Magnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string TI_path {
            get {
                return ResourceManager.GetString("TI_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces:.
        /// </summary>
        public static string TI_Pieces {
            get {
                return ResourceManager.GetString("TI_Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string TI_Progress {
            get {
                return ResourceManager.GetString("TI_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        public static string TI_Status_Checking {
            get {
                return ResourceManager.GetString("TI_Status_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check pending.
        /// </summary>
        public static string TI_Status_CheckPending {
            get {
                return ResourceManager.GetString("TI_Status_CheckPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downlaod pending.
        /// </summary>
        public static string TI_Status_download_pending {
            get {
                return ResourceManager.GetString("TI_Status_download_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string TI_Status_Downloading {
            get {
                return ResourceManager.GetString("TI_Status_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeding.
        /// </summary>
        public static string TI_Status_Seeding {
            get {
                return ResourceManager.GetString("TI_Status_Seeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed pending.
        /// </summary>
        public static string TI_Status_SeedPending {
            get {
                return ResourceManager.GetString("TI_Status_SeedPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string TI_Status_Stopped {
            get {
                return ResourceManager.GetString("TI_Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size:.
        /// </summary>
        public static string TI_TotalSize {
            get {
                return ResourceManager.GetString("TI_TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string TI_webSeedsConnected {
            get {
                return ResourceManager.GetString("TI_webSeedsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string TI_webSeedsOF {
            get {
                return ResourceManager.GetString("TI_webSeedsOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torrent.
        /// </summary>
        public static string Title_AddTorrentDialog {
            get {
                return ResourceManager.GetString("Title_AddTorrentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum download speed:.
        /// </summary>
        public static string TP_MaximumDownloadSp {
            get {
                return ResourceManager.GetString("TP_MaximumDownloadSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum upload speed:.
        /// </summary>
        public static string TP_MaximumUploadSp {
            get {
                return ResourceManager.GetString("TP_MaximumUploadSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer limit:.
        /// </summary>
        public static string TP_PeerLimit {
            get {
                return ResourceManager.GetString("TP_PeerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties:.
        /// </summary>
        public static string TP_Properties {
            get {
                return ResourceManager.GetString("TP_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed ratio:.
        /// </summary>
        public static string TP_SeedRatio {
            get {
                return ResourceManager.GetString("TP_SeedRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop seeding when inactive for:.
        /// </summary>
        public static string TP_StopSeed {
            get {
                return ResourceManager.GetString("TP_StopSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torrents selected.
        /// </summary>
        public static string TP_TorrentsSelected {
            get {
                return ResourceManager.GetString("TP_TorrentsSelected", resourceCulture);
            }
        }
    }
}
